os: osx
osx_image: xcode7.3

before_install:
  - brew install shellcheck
  - brew tap Homebrew/bundle

install:
  - brew bundle --file=extensions/Brewfile

script:
  - shellcheck worker.sh sample.worker.local ./**/*.sh
